version: '3.8'
services:
  # バックエンド (Go)
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./openapi:/openapi # OpenAPIファイルを共有
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase?sslmode=disable

  # フロントエンド (Next.js)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # node_modulesが上書きされないように
      - ./openapi:/openapi # OpenAPIファイルを共有
    tty: true # コンテナを起動し続けるため

  # データベース (PostgreSQL)
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: